// For adding custom fonts with other frameworks, see:
// https://tailwindcss.com/docs/font-family
import type { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'
import { Poppins, Libre_Baskerville, IBM_Plex_Mono } from 'next/font/google'
import { UserProvider } from '../_providers/user-provider'
import './globals.css'
import TanstackQueryProvider from '../_providers/tanstack-query'

const fontSans = Poppins({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: ['400', '500', '600'],
})

const fontSerif = Libre_Baskerville({
  subsets: ['latin'],
  variable: '--font-serif',
})

const fontMono = IBM_Plex_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  weight: ['400', '500', '600'],
})

export const metadata: Metadata = {
  title: 'Sound Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
      >
        <UserProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <TanstackQueryProvider>
              {children}
              {modal}
            </TanstackQueryProvider>
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  )
}
